# syntax=docker/dockerfile:1
ARG VARIANT="18-bookworm"
FROM mcr.microsoft.com/devcontainers/javascript-node:0-${VARIANT}

# [Optional] Install system dependencies
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment this to install additional OS packages.
# RUN apt-get update && apt-get install -y <your-package-name-here>

# [Optional] Uncomment this to install global node packages.
# RUN su node -c "npm install -g <your-package-here>"
